version: "3.4"
services:
  postgres:
    image: postgres:10.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=kong
      - POSTGRES_USER=kong

  migrator:
    image: kong:1.0.1-alpine
    restart: on-failure
    depends_on:
      - postgres
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
      - KONG_PG_DATABASE=kong
    command: kong migrations bootstrap
  
  kong:
    image: kong:1.0.1-alpine
    restart: unless-stopped
    depends_on: 
      - migrator
      - postgres
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
      - KONG_LOG_LEVEL=debug
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_LISTEN=0.0.0.0:8000
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444

  set-up:
    build: .
    image: set-up
    restart: on-failure
    depends_on: 
      - kong
    volumes: 
      - .:${PWD}
    environment: 
      - KONG_ADMIN_URL=http://kong:8001
    working_dir: ${PWD}
    command: ./set-up.sh
    